### ISSUE TITLE
Is a future feature use directly a odoo object for this library?

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/cfdilib#45]
A good extra feature is receive directly a `odoo` object to get a XML
Using minimal code from odoo like as:

```python
from cfdilib import cfdilibv3_odoo
from odoo import models

class Invoice(models.Model):
   @api.one
   def  get_xml(self):
        xml = cfdilibv3_odoo.get_xml(self)
        return xml
```

I remember a meeting talking about this approach but I don't know if It is planned or was discarded.

Thanks!

**Comment by nhomar** [comment]
I discarded this approach, because I need the feature on cfdilib be agnostic to odoo 100% , Why? odoo changes too much between versions and honestly ist is far more simple migrate 2 methods in odoo than in the lib between versions.

**Comment by moylop260** [comment]
I searched the xmind of that meeting but I don't found it

I remember the initial focus of this library was receive multi inputs:
 - dict, json, self-xml, odoo object, other object1, other object2...

Then the final decision was discard them and receive just `dict` (like as a bypass of `jinja2` library)?

**Comment by nhomar** [comment]
Then the final decision was discard them and receive just dict (like as a bypass of jinja2 library)?
Is right?:

Just as note.

- This will start from dict to xml using xsd as frame to build the objects (as objectify).
- Due to the fact of objectify in lxml the xml-conversion is not required anymore, just a wrapper for that.
- json is conceptually embeded due the fact that convert a json to a dict is already done by json lib then the json conversion is implicitaly included.

The odoo-dict conversion is done already by the .read() method, then in odoo itself we do only a mappind (this mapping is necesary anyway due the fact that cfdi fields do not have the same name as odoo fields.

I do not remember other option, but I just expect it left this as documentation for future proposals.

**Comment by moylop260** [comment]
Thanks for reply
